uth_groups/urls.py
from django.contrib import admin
from django.urls import path, include
from allauth.account.views import LoginView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('uth_groups_app.urls')),
    path('accounts/', include('allauth.urls')),
]

uth_groups_app/urls.py
from django.urls import path ,include
from django.conf.urls import url
from . import views

urlpatterns = [
    path('accounts/login/', views.index, name='home'),
    path('accounts/signup/', views.index, name='home'),
    path('accounts/password/set/', views.index, name='home'),
    path('accounts/inactive/', views.index, name='home'),
    path('accounts/email/', views.index, name='home'),
    path('accounts/confirm-email/', views.index, name='home'),
    path('accounts/social/', views.index, name='home'),
    path('accounts/google/', views.index, name='home'),
    url(r'accounts/social/', views.index, name='index'),
    url(r'accounts/password/', views.index, name='index'),

    
    path('', views.index, name='home'),
    path('privacy-policy/', views.privacypolicy, name='privacypolicy'),
    path('academicAuthorization/', views.academicAuthorization, name='academicAuthorization'),
    path('backAcademicAuthorization/', views.backAcademicAuthorization, name='backAcademicAuthorization'),
    path('cancelAcademicAuthorization/', views.cancelAcademicAuthorization, name='cancelAcademicAuthorization'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('calendar/', views.calendar, name='calendar'),
    path('profile/', views.profile, name='profile'),
    path('new/', views.new, name='new'),
    path('logout/', views.logout_user, name='logout_user'),
    path('groupsearch/', views.groupsearch, name='groupsearch'),
    path('add/', views.add, name='add'),
    path('add/create', views.createam, name='createam'),
    path('addcourse/', views.add_course, name='add-course'),
    path('course/<str:course_id>', views.coursePage, name='coursePage'),
    path('course/<slug:course_id>/newgroup/creategroup/', views.creategroup, name='creategroup'),
    path('course/<slug:course_id>/group/<slug:group_id>', views.groupPage, name='groupPage'),
    path('renderfolder/', views.renderfolder, name='renderfolder'),
    path('about/', views.about, name='about'),
    path('change/', views.change_private, name='private'),
    path('create-code/', views.create_code, name='create_code'),
    path('delete-code/', views.delete_code, name='delete_code'),
    path('team-change/', views.team_change_private, name='team_private'),
    path('team-members/', views.handle_join_request, name='handle_join_request'),
    path('kick-members/', views.handle_kick_user, name='handle_kick_user'),
    path('group-members/', views.handle_join_request_group, name='handle_join_request_group'),
    path('kick-group-members/', views.handle_kick_user_group, name='handle_kick_user_group'),
    path('kick-admin/', views.handle_remove_admin_request, name='handle_remove_admin_request'),
    path('make-admin/', views.handle_make_admin_user, name='handle_make_admin_user'),
    path('kick-admin-group/', views.handle_remove_admin_request_group, name='handle_remove_admin_request_group'),
    path('make-admin-group/', views.handle_make_admin_user_group, name='handle_make_admin_user_group'),
    path('team-create-code/', views.team_create_code, name='team_create_code'),
    path('team-delete-code/', views.team_delete_code, name='team_delete_code'),
    path('deletefilefolder/', views.deletefilefolder, name='deletefilefolder'),
    path('course/<slug:course_id>/new-meet/', views.new_meet, name='new_meet'),
    path('course/<slug:course_id>/group/<slug:group_id>/new-meet/', views.new_meet, name='new_meet'),
    path('send_message', views.send_message, name='send_message'),
    path('refresh_chat/', views.refresh_chat, name='refresh_chat'),
    
    
    
    

    #uploaders
    path('control/', views.control, name='control'),
    path('upload', views.upload_file, name='upload_file'),
    path('createfolder', views.create_folder, name='create_folder'),
    #path('control/initdrive', views.initdrive, name='initdrive')
]

uth_groups_app/models.py
from operator import mod
from django.db import models
from django.contrib.auth.models import User

import os
import uuid

from django.db import models
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _

class Student(models.Model):
    user = models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    description = models.CharField(max_length=2000,default="",blank=True,null=True)
    root_folder_id = models.CharField(max_length=200,default="",blank=True,null=True)
    calendar_id = models.CharField(max_length=200,default="",blank=True,null=True)
    is_academic_authorized = models.BooleanField(default=False)
    academic_email = models.CharField(max_length=200,default=None,blank=True,null=True)
    authorization_code = models.CharField(max_length=200,default=None,blank=True,null=True)
    def __str__(self):
        return (self.user.first_name + " " + self.user.last_name)

class Message(models.Model):
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    message = models.CharField(max_length=2000,default="",blank=True,null=True)
    sended_at = models.DateTimeField(auto_now_add=True)

class Course(models.Model):
    owner = models.ForeignKey(Student,related_name='TeamOwner',on_delete=models.CASCADE,null=True)
    course_name = models.CharField(max_length=200)
    participants = models.ManyToManyField(Student,related_name='Participants')
    join_requests = models.ManyToManyField(Student,related_name='CourseJoinRequests')
    admins = models.ManyToManyField(Student,related_name='CourseAdmins')
    chat_messages = models.ManyToManyField(Message,related_name='ChatMessages')
    private = models.BooleanField(default=False)
    datetime = models.CharField(max_length=200,default=" ")
    folder_id = models.CharField(max_length=200,null=True)
    files_folder_id = models.CharField(max_length=200,null=True)
    code = models.CharField(max_length=200,null=True,default=None) 
    def __str__(self):
        return self.course_name

class Group(models.Model):
    owner = models.ForeignKey(Student,related_name='Owner',on_delete=models.CASCADE)
    title = models.CharField(max_length=200,null=True)
    datetime = models.CharField(max_length=200,default=" ")
    description = models.TextField(max_length=2000,blank=True)
    course = models.ForeignKey(Course,on_delete=models.CASCADE) #from student courses
    private = models.BooleanField(default=False)
    participants = models.ManyToManyField(Student)
    join_requests = models.ManyToManyField(Student,related_name='GroupJoinRequests')
    admins = models.ManyToManyField(Student,related_name='GroupAdmins')
    chat_messages = models.ManyToManyField(Message,related_name='ChatMessagesGroup')
    root_id = models.CharField(max_length=200,null=True)
    code = models.CharField(max_length=200,null=True,default=None)
    def __str__(self):
        return (self.title)


class Course_root_folders_ids(models.Model):
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    root_id = models.CharField(max_length=200,null=True)
    root_files_id = models.CharField(max_length=200,null=True)
    root_groups = models.CharField(max_length=200,null=True)
    def __str__(self):
        return self.root_id

class Group_root_folders_ids(models.Model):
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    group = models.ForeignKey(Group,on_delete=models.CASCADE,null=True)
    root_id = models.CharField(max_length=200,null=True)
    shorcut_id = models.CharField(max_length=200,null=True)
    def __str__(self):
        return self.root_id

class Uploader(models.Model):
    user = models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    total_space = models.BigIntegerField(default=0)
    used_space = models.BigIntegerField(default=0)
    available_space = models.BigIntegerField(default=0)
    total_space_str = models.CharField(max_length=200,default=0)
    used_space_str = models.CharField(max_length=200,default=0)
    available_space_str = models.CharField(max_length=200,default=0)
    base_id = models.CharField(max_length=200,default=0)
    shorcut_id = models.CharField(max_length=200,default=0)
    active = models.BooleanField(default=False)
    def __str__(self):
        return (self.user.email)

class UploadedFile(models.Model):
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    course = models.ForeignKey(Course,on_delete=models.CASCADE,null=True,default=None)
    group = models.ForeignKey(Group,on_delete=models.CASCADE,null=True,default=None)
    folder_id = models.CharField(max_length=200,null=True)
    filename = models.CharField(max_length=200,null=True)
    file = models.FileField()


class GoogleEvent(models.Model):
    iCalUID = models.CharField(max_length=200,null=True)
    owner = models.ForeignKey(Student,on_delete=models.CASCADE,related_name='EventOwner',null=True,default=None)
    participants = models.ManyToManyField(Student)
    course = models.ForeignKey(Course,on_delete=models.CASCADE,null=True,default=None)
    group = models.ForeignKey(Group,on_delete=models.CASCADE,null=True,default=None)





@receiver(models.signals.post_delete, sender=UploadedFile)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.file:
        if os.path.isfile(instance.file.path):
            os.remove(instance.file.path)

uth_groups_app/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from .models import *

class UploadFileForm(forms.Form):
    files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

uth_groups_app/templates/uth_groups_app/authenticated/courses/add.html
{% extends 'uth_groups_app/authenticated/authed_main.html' %}
{%load static%}
{% block head %}
<title>
	Δημιουργία και συμμετοχή σε ομάδα · Uth Groups
</title>
{% endblock %}
{% load account %}
{% block selected_tab %}
<style>
.hideLoadSettings{
display:None;
}
</style>
<ul class="nav">
	<li>
		<a href={% url 'dashboard' %}>
		<i class="fas fa-users"></i>
		<p>Οι Ομαδες μου</p>
		</a>
	</li>
	<li class="active">
		<a href={% url 'add' %}>
		<i class="fas fa-plus-circle"></i>
		<p>Νεα ομαδα</p>
		</a>
	</li>
	<li>
		<a href={% url 'calendar' %}>
		<i class="far fa-calendar-alt"></i>
		<p>Ημερολoγιο</p>
		</a>
	</li>
	<li >
		<a href={% url 'profile' %}>
		<i class="far fa-user-circle"></i>
		<p>Προφιλ</p>
		</a>
	</li>
</ul>
{% endblock  %}
{% block page_title %}
<a class="navbar-brand" >Δημιουργία και συμμετοχή σε ομάδα</a>  
{% endblock %}
{% block content %}
<div class="content">
<div class="row">
	<div class="col-lg-6 col-md-6 col-sm-12">
		<div class="card card-stats">
			<div class="card-body ">
				<div class="row">
					<div class="col-5 col-md-4">
						<div class="icon-big text-center icon-warning">
							<i class="fas fa-user-plus" style="color: #d03636;"></i>
						</div>
					</div>
					<div class="col-7 col-md-8">
						<div class="numbers">
							<p class="card-title text-secondary">Δημιουργήστε μια ομάδα
							<p>
						</div>
					</div>
				</div>
			</div>
			<div class="card-footer ">
				<br>
				<hr>
				<div class="stats">
					<br>
					<div class="text-center">
						<a href={% url 'createam' %}><button type="sumbit" class="btn btn-fill">Δημιουργια ομαδας</button></a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-12">
		<div class="card card-stats">
			<div class="card-body ">
				<div class="row">
					<div class="col-5 col-md-4">
						<div class="icon-big text-center icon-warning">
							<i class="fas fa-sign-in-alt danger" style="color: #d03636;"></i>
						</div>
					</div>
					<div class="col-7 col-md-8">
						<div class="numbers">
							<p class="card-title text-secondary">Eγγραφείτε σε μια ομάδα<br> ή group με κωδικό
							<p>
						</div>
					</div>
				</div>
				<div class="card-footer ">
					<hr>
					<div class="stats">
						<form method="post">
							{% csrf_token %}
							<input type="text" class="form-control border-input" id="code" name="code" placeholder="Καταχωρήστε κωδικό">
							<br>
							<div class="text-center">
								<button type="sumbit" class="btn btn-fill" href="#">Συμμετοχη</button>
							</div>
						</form>
					</div>
				</div>
				
			</div>
			
		</div>
	</div>
	<div class="mx-auto">
		<p style="color:red;"><b>{{err}}</b></p>
	</div>
	<div class="col-lg-12 col-md-6 col-sm-12">
	<br><hr>
		<h5>Αναζήτηση ομάδας με όνομα</h5>
		<form class="navbar-form " id="groupsearch" courses-url="{% url 'groupsearch' %}">
			<input class="custom-select custom-select-lg mb-3 bg-light border-dark " name="course" id="course" style="font-family: 'Roboto Slab', serif" placeholder="Όνομα ομάδας">
		</form>
	</div>
	<div class="input-field col s12" id="id_course">
		<div id="loadingSettings" class="spinner-border hideLoadSettings" role="status">
			<span class="sr-only">Loading...</span>
		</div>
	</div>
</div>
{% endblock content %}
{% block scripts%}
<script>
	$("#course").keyup(function () {
		$("#loadingSettings").toggleClass("hideLoadSettings");
	    var url = $("#groupsearch").attr("courses-url"); 
	    var searched = $(this).val();  
	    
	    $.ajax({                  
	        url: url,                   
	        data: {
	            'searched': searched
	        },
	        success: function (data) {   
	            $("#id_course").html(data);  
	        }
	  });
	
	});
</script>
{% endblock scripts%}

uth_groups_app/templates/uth_groups_app/authenticated/courses/createam.html
{% extends 'uth_groups_app/authenticated/authed_main.html' %}
{%load static%}
{% block head %}
<title>
	Δημιουργία Ομάδας · Uth Groups
</title>
<style> 
	textarea {
	width: 100%;
	height: 150px;
	padding: 12px 20px;
	box-sizing: border-box;
	border: 2px solid #ccc;
	border-radius: 4px;
	background-color: #f8f8f8;
	border-color: black;
	font-size: 16px;
	}
</style>
{% endblock %}
{% load account %}
{% block page_title %}
<a class="navbar-brand" href="javascript:;">Δημιουργία Ομάδας</a>  
{% endblock %}
{% block selected_tab %}
<ul class="nav">
	<li>
		<a href={% url 'dashboard' %}>
		<i class="fas fa-users"></i>
		<p>Οι Ομαδες μου</p>
		</a>
	</li>
	<li class="active">
		<a href={% url 'add' %}>
		<i class="fas fa-plus-circle"></i>
		<p>Νεα ομαδα</p>
		</a>
	</li>
	<li>
		<a href={% url 'calendar' %}>
		<i class="far fa-calendar-alt"></i>
		<p>Ημερολoγιο</p>
		</a>
	</li>
	<li >
		<a href={% url 'profile' %}>
		<i class="far fa-user-circle"></i>
		<p>Προφιλ</p>
		</a>
	</li>
</ul>
{% endblock  %}
{% block content %}
<div class="content">
<div class="row">
	<div class="col-md-7 order-md-4 mx-auto">
		<h5><b>{{error_message}}</b></h5>
		<h4 class="mb-3">Δημιουργία Ομάδας</h4>
		<form method='POST'>
			{% csrf_token %}
			<div class="row" class="row" novalidate>
				<div class="col-md-12 mb-3">
					<label for="team_name">Όνομα Ομάδας</label>
					<input type="text" class="form-control" id="team_name" name="team_name" placeholder="Όνομα Ομάδας ..." value="{{temp_teamname}}" required>
					<div class="invalid-feedback">
						Δώστε ένα όνομα για την ομάδα σας.
					</div>
					<p style="color:red">{{message}}
					<p>
				</div>
			</div>
			<div class="mb-3">
				<label for="description">Περιγραφή</label>
				<textarea type="text" id="description" name="description" placeholder="Δώστε μια περιγραφή για την ομάδα ..." >{{temp_team_description}}</textarea>
			</div>
			<div class="mb-3">
				<div class="custom-control custom-switch mx-auto">
					<input type="checkbox" class="custom-control-input" id="private" name="private">
					<label class="custom-control-label no-needs-validation" for="private"><b>Ιδιωτική Ομάδα</b> - Εσείς διαλέγεται ποιός μπορεί να μπεί στην ομάδα.
					Στην καρτέλα "Επιλογές" μπορείτε να διαχειριστείτε τις αιτήσεις άλλων χρηστών προς την ομάδα σας.</label>
				</div>
				<hr class="mb-4">
				<button class="btn btn-light btn-block" type="submit">Δημιουργια</button>
		</form>
		</div>
	</div>
</div>
{% endblock content %}
{% block scripts%}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="{% static 'authenticated/js/form-validation.js' %}"></script>
{%endblock scripts%}

uth_groups_app/templates/uth_groups_app/authenticated/courses/member_team_changes.html
{%load static%}
	<style>
	.table tr {
    cursor: pointer;
	}
  .hideLoadSettings{
    display:None;
  }
	</style>

<div id="rendered_members">
  <div id="loadingSettings" class="spinner-border hideLoadSettings" role="status">
    <span class="sr-only">Loading...</span>
  </div>
  <h4>Διαχειρηστές</h4>
  {% if admins%}
    <table class="table table-hover">
      <thead class="thead-light">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Ονομα χρηστη</th>
          <th scope="col">Gmail</th>
          <th scope="col">Ακαδημαϊκo Email</th>
          <th scope="col">Ενεργεια</th>
        </tr>
      </thead>
      <tbody>
      {% for admin in admins%}
        <tr>
          <th scope="row"><img width="30" height="30" class="rounded-circle" src="{{ admin.user.socialaccount_set.all.0.get_avatar_url }}" alt="..."></th>
          <td>{{admin}}</td>
          <td>{{admin.user.email}}</td>
          <td>{{admin.academic_email}}</td>
          <td>
            <a id="removeAdmin-{{admin.pk}}" data-value={{admin.pk}} team="{{course.pk}}" handle-remove-admin-request-url="{% url 'handle_remove_admin_request' %}" onclick="handleRemoveAdmin('{{admin.pk}}')"style="color:red;">Διαγραφή απο τους διαχειρηστές</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {%else%}
  Δεν υπάρχουν διαχειρηστές
  {% endif %}
  <h4>Μέλη</h4>
  {% if participants %}
    <p>Με την επιλογή "Διαχειριστής" μπορείτε να κάνετε κάποιον χρήστη διαχειρηστή , οι διαχειρηστές έχουν πλήρη πρόσβαση σε όλες τις επιλογές της ομάδας
    <b>εκτός</b> από το να διαγράψουν την ομάδα.
    <table class="table table-hover">
      <thead class="thead-light">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Ονομα χρηστη</th>
          <th scope="col">Gmail</th>
          <th scope="col">Ακαδημαϊκo Email</th>
          <th scope="col">Ενεργεια</th>
        </tr>
      </thead>
      <tbody>
      {% for member in participants%}
        <tr>
          <th scope="row"><img width="30" height="30" class="rounded-circle" src="{{ member.user.socialaccount_set.all.0.get_avatar_url }}" alt="..."></th>
          <td>{{member}}</td>
          <td>{{member.user.email}}</td>
          <td>{{member.academic_email}}</td>
          <td>
            <a id="makeUserAdmin-{{member.pk}}" data-value={{member.pk}} team="{{course.pk}}" handle-make-user-admin-url="{% url 'handle_make_admin_user' %}" onclick="handleMakeAdminUser('{{member.pk}}')"style="color:green;">Διαχειριστής</a>
            /
            <a id="kickUser-{{member.pk}}" data-value={{member.pk}} team="{{course.pk}}" handle-kick-user-url="{% url 'handle_kick_user' %}" onclick="handleKickUser('{{member.pk}}')"style="color:red;">Διαγραφή</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {%else%}
  Δεν υπάρχουν μέλη
  {% endif %}

  <h4>Αιτήματα</h4>
  {% if join_requests%}
    <table class="table table-hover">
      <thead class="thead-light">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Ονομα χρηστη</th>
          <th scope="col">Gmail</th>
          <th scope="col">Ακαδημαϊκo Email</th>
          <th scope="col">Ενεργεια</th>
        </tr>
      </thead>
      <tbody>
      {% for requester in join_requests%}
        <tr>
          <th scope="row"><img width="30" height="30" class="rounded-circle" src="{{ requester.user.socialaccount_set.all.0.get_avatar_url }}" alt="..."></th>
          <td>{{requester}}</td>
          <td>{{requester.user.email}}</td>
          <td>{{requester.academic_email}}</td>
          <td>
            <a id="joinRequest-{{requester.pk}}" data-value={{requester.pk}} team="{{course.pk}}" handle-join-request-url="{% url 'handle_join_request' %}" onclick="handleJoinRequest('{{requester.pk}}','Accept')"style="color:green;">Aποδοχή</a>
            /
            <a id="joinRequest-{{requester.pk}}" data-value={{requester.pk}} team="{{course.pk}}" handle-join-request-url="{% url 'handle_join_request' %}" onclick="handleJoinRequest('{{requester.pk}}','Decline')"style="color:red;">Απόρριψη</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {%else%}
  Δεν υπάρχουν αιτήματα
  {% endif %}
</div>

{%block scripts%}
<script>
function handleJoinRequest(requester_id,status){
    $("#loadingSettings").toggleClass("hideLoadSettings");
	  id = "#joinRequest-" + requester_id
	  var url = $(id).attr("handle-join-request-url");
	  var team = $(id).attr("team");
      $.ajax({
        url: url,                   
	      data: {
			  'status':status,
	      'requester_id': requester_id,
        'team':team
	      },
	      success: function (data) {   
	          $("#rendered_members").html(data);  
	      }
	    });
}

function handleKickUser(requester_id){
    $("#loadingSettings").toggleClass("hideLoadSettings");
	  id = "#kickUser-" + requester_id
	  var url = $(id).attr("handle-kick-user-url");
	  var team = $(id).attr("team");
      $.ajax({
        url: url,                   
	      data: {
	      'requester_id': requester_id,
        'team':team
	      },
	      success: function (data) {   
	          $("#rendered_members").html(data);  
	      }
	    });
}

function handleRemoveAdmin(requester_id){
    $("#loadingSettings").toggleClass("hideLoadSettings");
	  id = "#removeAdmin-" + requester_id
	  var url = $(id).attr("handle-remove-admin-request-url");
	  var team = $(id).attr("team");
      $.ajax({
        url: url,                   
	      data: {
	      'requester_id': requester_id,
        'team':team
	      },
	      success: function (data) {   
	          $("#rendered_members").html(data);  
	      }
	    });
}

function handleMakeAdminUser(requester_id){
    $("#loadingSettings").toggleClass("hideLoadSettings");
	  id = "#makeUserAdmin-" + requester_id
	  var url = $(id).attr("handle-make-user-admin-url");
	  var team = $(id).attr("team");
      $.ajax({
        url: url,                   
	      data: {
	      'requester_id': requester_id,
        'team':team
	      },
	      success: function (data) {   
	          $("#rendered_members").html(data);  
	      }
	    });
}
</script>
{% endblock scripts%}

uth_groups_app/templates/uth_groups_app/authenticated/courses/team_changes.html
<div id="change_render">
	{% if course.code == None %}
		<div class="d-flex justify-content-center">
			<b><p>Δημιουργίστε έναν κωδικό συμμετοχής για την ομάδα σας. <br>Οποιοδσήποτε έχει τον κωδικό συμμετοχής μπορεί να μπει στην ομάδα σας.</p></b>
		</div>
		<div class="d-flex justify-content-center">
			<form id="create_code_form" data-value={{course.pk}} create-code-form-url="{% url 'team_create_code' %}">
				<a id="create_code" class="btn btn-light btn-sm" style="color:white;">Δημιουργια Κωδικου</a>
			</form>
		</div>
	{% else %}
		<div class="d-flex justify-content-center">
			<b><p>Οποιοδσήποτε έχει τον κωδικό συμμετοχής μπορεί να μπει στην ομάδα σας.</p></b>
		</div>
		<div class="d-flex justify-content-center">
			<input type="text" class="form-control" value={{course.code}} id="myInput" name="myInput" readonly="readonly">
			<form id="refresh_code_form" data-value={{course.pk}} refresh-code-form-url="{% url 'team_create_code' %}">
				<a id="refresh_code" class="btn btn-light btn-sm" style="color:white;">Ανανεωση κωδικου</a>
			</form>			
		</div>
		<div class="d-flex justify-content-center">
			<form id="delete_code_form" data-value={{course.pk}} delete-code-form-url="{% url 'team_delete_code' %}">
				<div class="d-flex">
					<div class="p-2"><a href="#" onclick="copy_code()"><b>Αντιγραφή Κωδικού</b></a></div>
					<div class="ml-auto p-2"><a id="delete_code" href="#"><b>Διαγραφη Κωδικου</b></a></div>
				</div>
			</form>
		</div>
	{% endif %}
</div>

{% block scripts%}
<script>
$("#private_checkbox").change(function () {
	var url = $("#private").attr("private-url"); 
	var course_id = $("#private").data("value"); 
	    
	$.ajax({                  
	    url: url,                   
	    data: {
	        'course_id': course_id
	    }
	});
	
});

$("#create_code").click(function () {
	var url = $("#create_code_form").attr("create-code-form-url"); 
	var course_id = $("#create_code_form").data("value"); 
	    
	$.ajax({                  
	    url: url,                   
	    data: {
	        'course_id': course_id
	    },
	    success: function (data) {   
	        $("#change_render").html(data);  
	    }
	});
	
});

$("#refresh_code").click(function () {
	var url = $("#refresh_code_form").attr("refresh-code-form-url"); 
	var course_id = $("#refresh_code_form").data("value"); 
	    
	$.ajax({                  
	    url: url,                   
	    data: {
	        'course_id': course_id
	    },
	    success: function (data) {   
	        $("#change_render").html(data);  
	    }
	});
	
});

$("#delete_code").click(function () {
	var url = $("#delete_code_form").attr("delete-code-form-url"); 
	var course_id = $("#delete_code_form").data("value"); 
	    
	$.ajax({                  
	    url: url,                   
	    data: {
	        'course_id': course_id
	    },
	    success: function (data) {   
	        $("#change_render").html(data);  
	    }
	});
	
});

function copy_code() {
  /* Get the text field */
  var copyText = document.getElementById("myInput");

  /* Select the text field */
  copyText.select();
  copyText.setSelectionRange(0, 99999); /* For mobile devices */

  /* Copy the text inside the text field */
  document.execCommand("copy");

}
</script>
{% endblock %}